//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BundleManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BundleManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("EnsureInstance", EnsureInstance);
		L.RegFunction("Instantiate", Instantiate);
		L.RegFunction("InstantiateAsync", InstantiateAsync);
		L.RegFunction("Contains", Contains);
		L.RegFunction("Release", Release);
		L.RegFunction("ReleaseInstance", ReleaseInstance);
		L.RegFunction("UnloadUnusedAssets", UnloadUnusedAssets);
		L.RegFunction("Clear", Clear);
		L.RegFunction("IsDependencyDownloaded", IsDependencyDownloaded);
		L.RegFunction("CheckAndDownloadDependencies", CheckAndDownloadDependencies);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("IsRemoteUpdateInProgress", get_IsRemoteUpdateInProgress, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EnsureInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			BundleManager o = BundleManager.EnsureInstance();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.GameObject o = obj.Instantiate(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 3);
				UnityEngine.GameObject o = obj.Instantiate(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 4)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
				UnityEngine.GameObject o = obj.Instantiate(arg0, arg1, arg2);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 5)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
				UnityEngine.Transform arg3 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 5);
				UnityEngine.GameObject o = obj.Instantiate(arg0, arg1, arg2, arg3);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: BundleManager.Instantiate");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstantiateAsync(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 3);
				System.Action<UnityEngine.GameObject> arg2 = (System.Action<UnityEngine.GameObject>)ToLua.CheckDelegate<System.Action<UnityEngine.GameObject>>(L, 4);
				obj.InstantiateAsync(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 6)
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
				UnityEngine.Transform arg3 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 5);
				System.Action<UnityEngine.GameObject> arg4 = (System.Action<UnityEngine.GameObject>)ToLua.CheckDelegate<System.Action<UnityEngine.GameObject>>(L, 6);
				obj.InstantiateAsync(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: BundleManager.InstantiateAsync");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Contains(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.Contains(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Release(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.Release(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.Object>(L, 2))
			{
				BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
				UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 2);
				obj.Release(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: BundleManager.Release");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.ReleaseInstance(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadUnusedAssets(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			obj.UnloadUnusedAssets();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsDependencyDownloaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsDependencyDownloaded(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CheckAndDownloadDependencies(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			BundleManager obj = (BundleManager)ToLua.CheckObject<BundleManager>(L, 1);
			System.Collections.Generic.IList<string> arg0 = (System.Collections.Generic.IList<string>)ToLua.CheckObject<System.Collections.Generic.IList<string>>(L, 2);
			System.Action<ResourceDownloadStatus> arg1 = (System.Action<ResourceDownloadStatus>)ToLua.CheckDelegate<System.Action<ResourceDownloadStatus>>(L, 3);
			System.Action arg2 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 4);
			System.Action<string> arg3 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 5);
			obj.CheckAndDownloadDependencies(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, BundleManager.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsRemoteUpdateInProgress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BundleManager obj = (BundleManager)o;
			bool ret = obj.IsRemoteUpdateInProgress;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsRemoteUpdateInProgress on a nil value");
		}
	}
}

