//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CameraManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CameraManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetMainCamera", GetMainCamera);
		L.RegFunction("GetVirtualCamera", GetVirtualCamera);
		L.RegFunction("Shake", Shake);
		L.RegFunction("StopShake", StopShake);
		L.RegFunction("ZoomTo", ZoomTo);
		L.RegFunction("SetOutdoorCamera", SetOutdoorCamera);
		L.RegFunction("SetIndoorCamera", SetIndoorCamera);
		L.RegFunction("IsOutdoor", IsOutdoor);
		L.RegFunction("GetCurrentOrtho", GetCurrentOrtho);
		L.RegFunction("ZoomBy", ZoomBy);
		L.RegFunction("ZoomIn", ZoomIn);
		L.RegFunction("ZoomOut", ZoomOut);
		L.RegFunction("SetZoom", SetZoom);
		L.RegFunction("SetFollowOffset", SetFollowOffset);
		L.RegFunction("PanToPosition", PanToPosition);
		L.RegFunction("SetFollowTarget", SetFollowTarget);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, set_instance);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMainCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			UnityEngine.Camera o = obj.GetMainCamera();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetVirtualCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			Cinemachine.CinemachineVirtualCamera o = obj.GetVirtualCamera();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Shake(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				obj.Shake();
				return 0;
			}
			else if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.Shake(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.Shake(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.Shake");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopShake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			obj.StopShake();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ZoomTo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.ZoomTo(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.ZoomTo(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.ZoomTo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetOutdoorCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			obj.SetOutdoorCamera();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIndoorCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			obj.SetIndoorCamera();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsOutdoor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			bool o = obj.IsOutdoor();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurrentOrtho(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			float o = obj.GetCurrentOrtho();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ZoomBy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.ZoomBy(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.ZoomBy(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.ZoomBy");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ZoomIn(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				obj.ZoomIn();
				return 0;
			}
			else if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.ZoomIn(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.ZoomIn");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ZoomOut(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				obj.ZoomOut();
				return 0;
			}
			else if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.ZoomOut(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.ZoomOut");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetZoom(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.SetZoom(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.SetZoom(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.SetZoom");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFollowOffset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.SetFollowOffset(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PanToPosition(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				obj.PanToPosition(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.PanToPosition(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.PanToPosition(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CameraManager.PanToPosition");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CameraManager obj = (CameraManager)ToLua.CheckObject<CameraManager>(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.SetFollowTarget(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, CameraManager.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_instance(IntPtr L)
	{
		try
		{
			CameraManager arg0 = (CameraManager)ToLua.CheckObject<CameraManager>(L, 2);
			CameraManager.instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

