//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class InputManager_GameButtonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(InputManager.GameButton));
		L.RegVar("Jump", get_Jump, null);
		L.RegVar("Dash", get_Dash, null);
		L.RegVar("Attack", get_Attack, null);
		L.RegVar("SuperDash", get_SuperDash, null);
		L.RegVar("FireBall", get_FireBall, null);
		L.RegVar("Heal", get_Heal, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<InputManager.GameButton>.Check = CheckType;
		StackTraits<InputManager.GameButton>.Push = Push;
	}

	static void Push(IntPtr L, InputManager.GameButton arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(InputManager.GameButton), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Jump(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.Jump);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Dash(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.Dash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Attack(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.Attack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SuperDash(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.SuperDash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FireBall(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.FireBall);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Heal(IntPtr L)
	{
		ToLua.Push(L, InputManager.GameButton.Heal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		InputManager.GameButton o = (InputManager.GameButton)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

