//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PlayerControllerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PlayerController), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("OnAttackEnd", OnAttackEnd);
		L.RegFunction("SetIsOnGround", SetIsOnGround);
		L.RegFunction("IsOnGround", IsOnGround);
		L.RegFunction("IsClimbing", IsClimbing);
		L.RegFunction("OnClimbStart", OnClimbStart);
		L.RegFunction("OnClimbEnd", OnClimbEnd);
		L.RegFunction("CanSuperDash", CanSuperDash);
		L.RegFunction("ApplyKnockback", ApplyKnockback);
		L.RegFunction("ResetAllParameters", ResetAllParameters);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAttackEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			obj.OnAttackEnd();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsOnGround(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsOnGround(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsOnGround(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			bool o = obj.IsOnGround();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsClimbing(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			bool o = obj.IsClimbing();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClimbStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			obj.OnClimbStart();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClimbEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			obj.OnClimbEnd();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CanSuperDash(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			bool o = obj.CanSuperDash();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ApplyKnockback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 3);
			obj.ApplyKnockback(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetAllParameters(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerController obj = (PlayerController)ToLua.CheckObject<PlayerController>(L, 1);
			obj.ResetAllParameters();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

