//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SaveManagerWrap
{
    public static void Register(LuaState L)
    {
        L.BeginClass(typeof(SaveManager), typeof(UnityEngine.MonoBehaviour));
        L.RegFunction("EnsureInstance", EnsureInstance);
        L.RegFunction("GetMaxSlotCount", GetMaxSlotCount);
        L.RegFunction("SaveCurrentGameAuto", SaveCurrentGameAuto);
        L.RegFunction("SaveCurrentGameToCurrentSlot", SaveCurrentGameToCurrentSlot);
        L.RegFunction("SaveCurrentGameToSlot", SaveCurrentGameToSlot);
        L.RegFunction("LoadSlotOrNewGame", LoadSlotOrNewGame);
        L.RegFunction("ContinueLastGame", ContinueLastGame);
        L.RegFunction("HasSlot", HasSlot);
        L.RegFunction("HasAnySlot", HasAnySlot);
        L.RegFunction("GetLastSlotId", GetLastSlotId);
        L.RegFunction("DeleteSlot", DeleteSlot);
        L.RegFunction("GetSlotLocationName", GetSlotLocationName);
        L.RegFunction("GetSlotPlayTimeText", GetSlotPlayTimeText);
        L.RegFunction("GetSlotCurrentHealth", GetSlotCurrentHealth);
        L.RegFunction("GetSlotMaxHealth", GetSlotMaxHealth);
        L.RegFunction("GetSlotSoulPowerRate", GetSlotSoulPowerRate);
        L.RegFunction("GetSlotIconPath", GetSlotIconPath);
        L.RegFunction("__eq", op_Equality);
        L.RegFunction("__tostring", ToLua.op_ToString);
        L.RegVar("Instance", get_Instance, null);
        L.EndClass();
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int EnsureInstance(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            SaveManager o = SaveManager.EnsureInstance();
            ToLua.Push(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetMaxSlotCount(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            int o = SaveManager.GetMaxSlotCount();
            LuaDLL.lua_pushinteger(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int SaveCurrentGameAuto(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            SaveManager.SaveCurrentGameAuto();
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int SaveCurrentGameToCurrentSlot(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            SaveManager.SaveCurrentGameToCurrentSlot();
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int SaveCurrentGameToSlot(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            SaveManager.SaveCurrentGameToSlot(arg0);
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int LoadSlotOrNewGame(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            SaveManager.LoadSlotOrNewGame(arg0);
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int ContinueLastGame(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            SaveManager.ContinueLastGame();
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int HasSlot(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            bool o = SaveManager.HasSlot(arg0);
            LuaDLL.lua_pushboolean(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int HasAnySlot(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            bool o = SaveManager.HasAnySlot();
            LuaDLL.lua_pushboolean(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetLastSlotId(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 0);
            int o = SaveManager.GetLastSlotId();
            LuaDLL.lua_pushinteger(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int DeleteSlot(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            SaveManager.DeleteSlot(arg0);
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotLocationName(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            string o = SaveManager.GetSlotLocationName(arg0);
            LuaDLL.lua_pushstring(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotPlayTimeText(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            string o = SaveManager.GetSlotPlayTimeText(arg0);
            LuaDLL.lua_pushstring(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotCurrentHealth(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            int o = SaveManager.GetSlotCurrentHealth(arg0);
            LuaDLL.lua_pushinteger(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotMaxHealth(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            int o = SaveManager.GetSlotMaxHealth(arg0);
            LuaDLL.lua_pushinteger(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotSoulPowerRate(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            float o = SaveManager.GetSlotSoulPowerRate(arg0);
            LuaDLL.lua_pushnumber(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetSlotIconPath(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            string o = SaveManager.GetSlotIconPath(arg0);
            LuaDLL.lua_pushstring(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int op_Equality(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 2);
            UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
            UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
            bool o = arg0 == arg1;
            LuaDLL.lua_pushboolean(L, o);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int get_Instance(IntPtr L)
    {
        try
        {
            ToLua.Push(L, SaveManager.Instance);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }
}
