//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TMPro_TMP_InputField_CharacterValidationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(TMPro.TMP_InputField.CharacterValidation));
		L.RegVar("None", get_None, null);
		L.RegVar("Digit", get_Digit, null);
		L.RegVar("Integer", get_Integer, null);
		L.RegVar("Decimal", get_Decimal, null);
		L.RegVar("Alphanumeric", get_Alphanumeric, null);
		L.RegVar("Name", get_Name, null);
		L.RegVar("Regex", get_Regex, null);
		L.RegVar("EmailAddress", get_EmailAddress, null);
		L.RegVar("CustomValidator", get_CustomValidator, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<TMPro.TMP_InputField.CharacterValidation>.Check = CheckType;
		StackTraits<TMPro.TMP_InputField.CharacterValidation>.Push = Push;
	}

	static void Push(IntPtr L, TMPro.TMP_InputField.CharacterValidation arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(TMPro.TMP_InputField.CharacterValidation), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Digit(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Digit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Integer(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Integer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Decimal(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Decimal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alphanumeric(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Alphanumeric);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Name);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Regex(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.Regex);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmailAddress(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.EmailAddress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CustomValidator(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.CharacterValidation.CustomValidator);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		TMPro.TMP_InputField.CharacterValidation o = (TMPro.TMP_InputField.CharacterValidation)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

