//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TMPro_TMP_InputField_ContentTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(TMPro.TMP_InputField.ContentType));
		L.RegVar("Standard", get_Standard, null);
		L.RegVar("Autocorrected", get_Autocorrected, null);
		L.RegVar("IntegerNumber", get_IntegerNumber, null);
		L.RegVar("DecimalNumber", get_DecimalNumber, null);
		L.RegVar("Alphanumeric", get_Alphanumeric, null);
		L.RegVar("Name", get_Name, null);
		L.RegVar("EmailAddress", get_EmailAddress, null);
		L.RegVar("Password", get_Password, null);
		L.RegVar("Pin", get_Pin, null);
		L.RegVar("Custom", get_Custom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<TMPro.TMP_InputField.ContentType>.Check = CheckType;
		StackTraits<TMPro.TMP_InputField.ContentType>.Push = Push;
	}

	static void Push(IntPtr L, TMPro.TMP_InputField.ContentType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(TMPro.TMP_InputField.ContentType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Standard(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Standard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Autocorrected(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Autocorrected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IntegerNumber(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.IntegerNumber);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DecimalNumber(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.DecimalNumber);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alphanumeric(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Alphanumeric);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Name);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmailAddress(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.EmailAddress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Password(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Password);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Pin(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Pin);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Custom(IntPtr L)
	{
		ToLua.Push(L, TMPro.TMP_InputField.ContentType.Custom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		TMPro.TMP_InputField.ContentType o = (TMPro.TMP_InputField.ContentType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

