//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_DefaultControlsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("DefaultControls");
		L.RegFunction("CreatePanel", CreatePanel);
		L.RegFunction("CreateButton", CreateButton);
		L.RegFunction("CreateText", CreateText);
		L.RegFunction("CreateImage", CreateImage);
		L.RegFunction("CreateRawImage", CreateRawImage);
		L.RegFunction("CreateSlider", CreateSlider);
		L.RegFunction("CreateScrollbar", CreateScrollbar);
		L.RegFunction("CreateToggle", CreateToggle);
		L.RegFunction("CreateInputField", CreateInputField);
		L.RegFunction("CreateDropdown", CreateDropdown);
		L.RegFunction("CreateScrollView", CreateScrollView);
		L.RegVar("factory", get_factory, set_factory);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreatePanel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreatePanel(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateButton(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateText(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateImage(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateRawImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateRawImage(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateSlider(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateSlider(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateScrollbar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateScrollbar(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateToggle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateToggle(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateInputField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateInputField(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateDropdown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateDropdown(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateScrollView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.DefaultControls.Resources arg0 = StackTraits<UnityEngine.UI.DefaultControls.Resources>.Check(L, 1);
			UnityEngine.GameObject o = UnityEngine.UI.DefaultControls.CreateScrollView(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_factory(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UnityEngine.UI.DefaultControls.factory);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_factory(IntPtr L)
	{
		try
		{
			UnityEngine.UI.DefaultControls.IFactoryControls arg0 = (UnityEngine.UI.DefaultControls.IFactoryControls)ToLua.CheckObject<UnityEngine.UI.DefaultControls.IFactoryControls>(L, 2);
			UnityEngine.UI.DefaultControls.factory = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

