//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Events_UnityEvent_UnityEngine_TouchScreenKeyboard_StatusWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>), typeof(UnityEngine.Events.UnityEventBase), "UnityEvent_UnityEngine_TouchScreenKeyboard_Status");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Invoke", Invoke);
		L.RegFunction("New", _CreateUnityEngine_Events_UnityEvent_UnityEngine_TouchScreenKeyboard_Status);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Events_UnityEvent_UnityEngine_TouchScreenKeyboard_Status(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status> obj = new UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status> obj = (UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>>(L, 1);
			UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status> arg0 = (UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status> obj = (UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>>(L, 1);
			UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status> arg0 = (UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<UnityEngine.TouchScreenKeyboard.Status>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status> obj = (UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<UnityEngine.TouchScreenKeyboard.Status>>(L, 1);
			UnityEngine.TouchScreenKeyboard.Status arg0 = (UnityEngine.TouchScreenKeyboard.Status)ToLua.CheckObject(L, 2, typeof(UnityEngine.TouchScreenKeyboard.Status));
			obj.Invoke(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

