//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_GridLayoutGroup_CornerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.GridLayoutGroup.Corner));
		L.RegVar("UpperLeft", get_UpperLeft, null);
		L.RegVar("UpperRight", get_UpperRight, null);
		L.RegVar("LowerLeft", get_LowerLeft, null);
		L.RegVar("LowerRight", get_LowerRight, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.UI.GridLayoutGroup.Corner>.Check = CheckType;
		StackTraits<UnityEngine.UI.GridLayoutGroup.Corner>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.GridLayoutGroup.Corner arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.UI.GridLayoutGroup.Corner), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpperLeft(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.GridLayoutGroup.Corner.UpperLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpperRight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.GridLayoutGroup.Corner.UpperRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LowerLeft(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.GridLayoutGroup.Corner.LowerLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LowerRight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.GridLayoutGroup.Corner.LowerRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.GridLayoutGroup.Corner o = (UnityEngine.UI.GridLayoutGroup.Corner)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

