//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_Toggle_ToggleTransitionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.Toggle.ToggleTransition));
		L.RegVar("None", get_None, null);
		L.RegVar("Fade", get_Fade, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.UI.Toggle.ToggleTransition>.Check = CheckType;
		StackTraits<UnityEngine.UI.Toggle.ToggleTransition>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.Toggle.ToggleTransition arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.UI.Toggle.ToggleTransition), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Toggle.ToggleTransition.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fade(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Toggle.ToggleTransition.Fade);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.Toggle.ToggleTransition o = (UnityEngine.UI.Toggle.ToggleTransition)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

